function JointVel = JointVel(dq1,dq2,dq3,dq4,dq5,l1,l2,l3,l4,l5,q1,q2,q3,q4,q5)
%JOINTVEL
%    JOINTVEL = JOINTVEL(DQ1,DQ2,DQ3,DQ4,DQ5,L1,L2,L3,L4,L5,Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Mar-2020 14:05:11

t2 = pi.*(1.0./2.0);
t3 = q1+t2;
t4 = sin(t3);
t5 = cos(t3);
t6 = dq1.*l1.*t5;
t7 = q2+t2;
t8 = sin(t7);
t9 = cos(t7);
t10 = dq2.*l2.*t9;
t11 = q3+t2;
t12 = q4+t2;
t13 = sin(t12);
t14 = dq4.*l4.*t13;
t15 = cos(t12);
t16 = q5+t2;
JointVel = [-dq1.*l1.*t4;t6;-dq1.*l1.*t4-dq2.*l2.*t8;t6+t10;-dq3.*l3.*sin(t11)-dq1.*l1.*t4-dq2.*l2.*t8;t6+t10+dq3.*l3.*cos(t11);t14-dq1.*l1.*t4-dq2.*l2.*t8;t6+t10-dq4.*l4.*t15;t14+dq5.*l5.*sin(t16)-dq1.*l1.*t4-dq2.*l2.*t8;t6+t10-dq5.*l5.*cos(t16)-dq4.*l4.*t15];
