function JointPos = JointPos(l1,l2,l3,l4,l5,q1,q2,q3,q4,q5)
%JOINTPOS
%    JOINTPOS = JOINTPOS(L1,L2,L3,L4,L5,Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Mar-2020 14:05:11

t2 = pi.*(1.0./2.0);
t3 = q1+t2;
t4 = cos(t3);
t5 = l1.*t4;
t6 = sin(t3);
t7 = l1.*t6;
t8 = q2+t2;
t9 = cos(t8);
t10 = l2.*t9;
t11 = sin(t8);
t12 = l2.*t11;
t13 = q3+t2;
t14 = q4+t2;
t15 = cos(t14);
t16 = sin(t14);
t17 = q5+t2;
JointPos = [t5;t7;t5+t10;t7+t12;t5+t10+l3.*cos(t13);t7+t12+l3.*sin(t13);t5+t10-l4.*t15;t7+t12-l4.*t16;t5+t10-l4.*t15-l5.*cos(t17);t7+t12-l4.*t16-l5.*sin(t17)];
