function relativeJointPos = relativeJointPos(q1,q2,q3,q4,q5)
%RELATIVEJOINTPOS
%    RELATIVEJOINTPOS = RELATIVEJOINTPOS(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Mar-2020 14:05:11

relativeJointPos = [q1;q1-q2;q2-q3;-q3+q4;-q4+q5];
