function relativeJointVel = relativeJointVel(dq1,dq2,dq3,dq4,dq5)
%RELATIVEJOINTVEL
%    RELATIVEJOINTVEL = RELATIVEJOINTVEL(DQ1,DQ2,DQ3,DQ4,DQ5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    16-Mar-2020 14:05:12

relativeJointVel = [dq1;dq1-dq2;dq2-dq3;-dq3+dq4;-dq4+dq5];
